version: "3"

services:
  blur-frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "8080:8080"
    image: blur-frontend:0.1.0

#  blur-backend:
#    build:
#      context: .
#      dockerfile: docker/frontend/Dockerfile
#    ports:
#      - "3000:3000"
#    image: blur-backend:0.1.0

